# app/routes/router.py

from fastapi import APIRouter
from typing import List
from app.schemas.chat_schema import ChatRequest, ChatResponse, Message
from app.services.llm_services import generate_chat_response

router = APIRouter()


@router.post("/", response_model=ChatResponse)
def chat_endpoint(chat_request: ChatRequest):
    """
    Accepts a chat request with a list of messages and returns
    a response generated by the LLM using OpenRouter API.
    """

    # Select the system prompt (template)
    template_file = f"app/prompts/{chat_request.template}.txt"
    with open(template_file, "r", encoding="utf-8") as f:
        system_prompt = f.read()
        
    temperature = chat_request.temperature if chat_request.temperature is not None else 0.7
    # Generate LLM response
    reply = generate_chat_response(chat_request.messages, system_prompt, temperature=temperature)

    # Return structured response
    return ChatResponse(
        reply=reply,
        # can be dynamic if you implement tool_call/refusal templates
        template_used=chat_request.template,
        refusal=False                # basic version; add refusal logic later
    )
