# app/routes/router.py

from fastapi import APIRouter
from typing import List
from app.schemas.chat_schema import ChatRequest, ChatResponse, Message
from app.services.llm_services import generate_chat_response

router = APIRouter()


@router.post("/", response_model=ChatResponse)
def chat_endpoint(chat_request: ChatRequest):
    """
    Accepts a chat request with a list of messages and returns
    a response generated by the LLM using OpenRouter API.
    """

    # Select the system prompt (template)
    system_prompt = (
        "You are Sirane, a cheerful AI assistant. "
        "Answer politely and concisely. "
        "Do not engage in sexual or violent topics."
    )

    # Generate LLM response
    reply = generate_chat_response(chat_request.messages, system_prompt)

    # Return structured response
    return ChatResponse(
        reply=reply,
        # can be dynamic if you implement tool_call/refusal templates
        template_used="task_spec",
        refusal=False                # basic version; add refusal logic later
    )
